name: Publish Conda Version

on:
  # test for now with pushing to this branch
  push:
    branches:
      - ac/conda_release
  release:
    types:
      - published

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip

      - name: Publish Python distribution to Conda
        uses: fcakyon/conda-publish-action@v1.3
        with:
          subDir: '.conda'
          anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: 'win osx linux'
